# Auto-generated by nixos-generate-config on the Mac Mini.
# Replace this file with the actual output after installing NixOS:
#
#   sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# Then copy it back into this repo.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder — replace with generated values
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  hardware.cpu.intel.updateMicrocode = true;
}
