use std::io::{self, Write};

use nostr_sdk::prelude::*;

fn main() {
    println!("=== Nostrbox Setup ===\n");

    let config_path = std::env::var("NOSTRBOX_CONFIG").unwrap_or_else(|_| "nostrbox.toml".into());

    if std::path::Path::new(&config_path).exists() {
        print!("Config file '{}' already exists. Overwrite? [y/N] ", config_path);
        io::stdout().flush().unwrap();
        let mut input = String::new();
        io::stdin().read_line(&mut input).unwrap();
        if !input.trim().eq_ignore_ascii_case("y") {
            println!("Aborted.");
            return;
        }
    }

    // Identity setup
    println!("Server identity (nsec):");
    println!("  1. Generate new keypair");
    println!("  2. Enter existing nsec");
    print!("\nChoice [1]: ");
    io::stdout().flush().unwrap();

    let mut choice = String::new();
    io::stdin().read_line(&mut choice).unwrap();
    let choice = choice.trim();

    let keys = if choice == "2" {
        print!("Enter nsec: ");
        io::stdout().flush().unwrap();
        let mut nsec_input = String::new();
        io::stdin().read_line(&mut nsec_input).unwrap();
        let nsec = nsec_input.trim();
        match SecretKey::parse(nsec) {
            Ok(sk) => Keys::new(sk),
            Err(e) => {
                eprintln!("Invalid nsec: {e}");
                std::process::exit(1);
            }
        }
    } else {
        println!("Generating new keypair...");
        Keys::generate()
    };

    let nsec = keys.secret_key().to_bech32().unwrap();
    let npub = keys.public_key().to_bech32().unwrap();

    println!("\n  npub: {npub}");
    println!("  nsec: {nsec}");

    // Port config
    print!("\nHTTP bind address [0.0.0.0:3000]: ");
    io::stdout().flush().unwrap();
    let mut bind = String::new();
    io::stdin().read_line(&mut bind).unwrap();
    let bind = bind.trim();
    let bind_address = if bind.is_empty() { "0.0.0.0:3000" } else { bind };

    print!("Relay port [7777]: ");
    io::stdout().flush().unwrap();
    let mut port_input = String::new();
    io::stdin().read_line(&mut port_input).unwrap();
    let port_str = port_input.trim();
    let relay_port: u16 = if port_str.is_empty() {
        7777
    } else {
        port_str.parse().unwrap_or_else(|_| {
            eprintln!("Invalid port number, using 7777");
            7777
        })
    };

    print!("Database path [nostrbox.db]: ");
    io::stdout().flush().unwrap();
    let mut db_input = String::new();
    io::stdin().read_line(&mut db_input).unwrap();
    let db = db_input.trim();
    let db_path = if db.is_empty() { "nostrbox.db" } else { db };

    // Write config
    let config = format!(
        r#"# Nostrbox configuration
# Generated by `just init`

bind_address = "{bind_address}"
db_path = "{db_path}"
web_dist_path = "web/dist"
identity_nsec = "{nsec}"
relay_port = {relay_port}
relay_urls = []
"#
    );

    std::fs::write(&config_path, &config).unwrap_or_else(|e| {
        eprintln!("Failed to write config: {e}");
        std::process::exit(1);
    });

    println!("\nConfig written to {config_path}");
    println!("\nNext steps:");
    println!("  just build    # build server + web");
    println!("  just run      # start nostrbox");
}
